Models/Deferral.cs
namespace R12VIS.Models
{
    public class Deferral
    {
        public int Id { get; set; }
        public string Reason { get; set; }
    }
}

Controllers/DeferralsController.cs
using R12VIS.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace R12VIS.Controllers
{
    public class DeferralsController : Controller
    {
        private DbContextR12 db = new DbContextR12();

        // GET: Deferrals
        public ActionResult Index()
        {
            return View(db.Deferrals.ToList());
        }

        // GET: Deferrals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deferral deferral = db.Deferrals.Find(id);
            if (deferral == null)
            {
                return HttpNotFound();
            }
            return View(deferral);
        }

        // GET: Deferrals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Deferrals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Reason")] Deferral deferral)
        {
            if (ModelState.IsValid)
            {
                db.Deferrals.Add(deferral);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(deferral);
        }

        // GET: Deferrals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deferral deferral = db.Deferrals.Find(id);
            if (deferral == null)
            {
                return HttpNotFound();
            }
            return View(deferral);
        }

        // POST: Deferrals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Reason")] Deferral deferral)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deferral).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deferral);
        }

        // GET: Deferrals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deferral deferral = db.Deferrals.Find(id);
            if (deferral == null)
            {
                return HttpNotFound();
            }
            return View(deferral);
        }

        // POST: Deferrals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Deferral deferral = db.Deferrals.Find(id);
            db.Deferrals.Remove(deferral);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Deferrals/Create.cshtml
@model R12VIS.Models.Deferral

@{
    ViewBag.Title = "Create";
}

<script>
    var navItem = document.getElementById('nav-item-file-maintenance');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('file-maintenance-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-file-maintenance-deferral');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Deferral</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Deferral</li>
                <li class="breadcrumb-item" active>Create</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Create</h5>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Reason, "Deferral Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Reason, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Reason, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col text-end pt-3">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                        <a href="@Url.Action("Index")" class="btn btn-outline-secondary">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->

Views/Deferrals/Delete.cshtml
@model R12VIS.Models.Deferral

@{
    ViewBag.Title = "Delete";
}

<script>
    var navItem = document.getElementById('nav-item-file-maintenance');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('file-maintenance-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-file-maintenance-deferral');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Deferral</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Deferral</li>
                <li class="breadcrumb-item active">Delete</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Delete</h5>
                        <div>
                            <h5>Are you sure you want to delete this Deferral?</h5>
                            <div>
                                <hr />
                                <dl class="dl-horizontal">
                                    <dt>
                                        Deferral Name
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => model.Reason)
                                    </dd>

                                </dl>

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="row">
                                        <div class="col text-end pt-3">
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                            <a href="@Url.Action("Index")" class="btn btn-outline-secondary">Back to List</a>

                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

Views/Deferrals/Details.cshtml
@model R12VIS.Models.Deferral

@{
    ViewBag.Title = "Details";
}

<script>
    var navItem = document.getElementById('nav-item-file-maintenance');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('file-maintenance-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-file-maintenance-deferral');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Deferral</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Deferral</li>
                <li class="breadcrumb-item" active>Details</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Deferral Details</h5>
                        <div>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    Deferral Name
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Reason)
                                </dd>
                            </dl>
                        </div>
                        <div class="row">
                            <div class="col text-end pt-3">
                                <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-outline-primary">Edit</a>
                                <a href="@Url.Action("Index")" class="btn btn-outline-secondary">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->

Views/Deferrals/Edit.cshtml
@model R12VIS.Models.Deferral

@{
    ViewBag.Title = "Edit";
}

<script>
    var navItem = document.getElementById('nav-item-file-maintenance');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('file-maintenance-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-file-maintenance-deferral');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Deferral</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Deferral</li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Update Deferral Details</h5>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Reason, "Deferral Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Reason, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Reason, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col text-end pt-3">
                                        <input type="submit" value="Update" class="btn btn-primary" />
                                        <a href="@Url.Action("Index")" class="btn btn-outline-secondary">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->

Views/Deferrals/Index.cshtml
@model IEnumerable<R12VIS.Models.Deferral>

@{
    ViewBag.Title = "Index";
}

<script>
    var navItem = document.getElementById('nav-item-file-maintenance');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('file-maintenance-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-file-maintenance-deferral');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Deferral</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Deferral</a></li>
                <li class="breadcrumb-item">Index</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Deferral List</h5>
                <p>
                    <a class="btn btn-primary" href="@Url.Action("Create", "Deferrals")"><i class="bi bi-person-add"></i> New </a>
                </p>
                <table class="table table-bordered" id="myTable">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Reason)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="width:90%">
                                @Html.DisplayFor(modelItem => item.Reason)
                            </td>
                            <td style="width:10%">
                                <a class="link-primary" href="@Url.Action("Edit", "Deferrals", new { id = item.Id })"><i class="bi bi-pencil-square"></i></a>
                                <a class="link-secondary" href="@Url.Action("Details", "Deferrals", new { id = item.Id })"><i class="bi bi-filter-square"></i></a>
                                <a class="link-danger" href="@Url.Action("Delete", "Deferrals", new { id = item.Id })"><i class="bi bi-trash"></i></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </section>

</main><!-- End #main -->


@section scripts
{
    <script src="~/Content/DataTable/cdn.datatables.net_1.13.4_js_jquery.dataTables.min.js"></script>
    @*<script src="~/Content/DataTable/cdn.datatables.net_1.13.4_js_dataTables.bootstrap5.min.js"></script>*@
    <script src="~/Content/DataTable2/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                "bordered": true,
                "columns": [
                    { "title": "Deferral Name" },
                    { "title": "" }
                ]
            });
        });
    </script>
}