Models/Vaccination_SC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination_SC
    {
        public int vaccination_id { get; set; }
        public Nullable<int> vaccination_person_id { get; set; }
        public Nullable<int> vaccination_region_id { get; set; }
        public Nullable<int> vaccination_city_municipality_id { get; set; }
        public Nullable<int> vaccination_barangay_id { get; set; }
        public Nullable<int> vaccination_vaccine_id { get; set; }
        public Nullable<System.DateTime> vaccination_date { get; set; }
        public string vaccination_vaccinator { get; set; }
        public Nullable<int> vaccination_provcine_id { get; set; }
    
        public virtual Vaccine_SC Vaccine_SC { get; set; }
    }
}

Controllers/VaccinationsCSController.cs
using Newtonsoft.Json;
using R12VIS.Models;
using R12VIS.Models.ViewModel;
using System;
using System.Linq;
using System.Web.Mvc;

namespace R12VIS.Controllers
{
    [UserAuthenticationFilter]

    public class VaccinationsCSController : Controller
    {
        DbContextR12 db = new DbContextR12();
        DbMRSpecialVacsEntities vpddb = new DbMRSpecialVacsEntities();
        DbR12VISEntities visdb = new DbR12VISEntities();
        DbSeniorCitizenVacsEntities scdb = new DbSeniorCitizenVacsEntities();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PreVaccinationCS()
        {
            var ethnic_group_list = db.EthnicGroups.Select(a => new { a.Id, a.IndigenousMember });
            var regions = db.Regions.Select(a => new { value = a.ID, text = a.RegionName }).ToList();
            var provinces = db.Provinces.Where(a => a.RegionID == 1).OrderBy(a => a.province_name).Select(a => new { value = a.province_id, text = a.province_name }).ToList();
            var suffixes = visdb.Suffixes.ToList();
            var religions = db.Religions.ToList();
            var educational_attainment_list = db.EducationalAttainment.ToList();
            var income_class = db.IncomeClass.ToList();
            var occupation = db.Occupation.ToList();

            SelectList siblingRank = new SelectList(new[]
                        {
                new { Value = 1, Text = "First Born Child"},
                new { Value = 2, Text = "Second Born Child"},
                new { Value = 3, Text = "Third Born Child"},
                new { Value = 4, Text = "Fourth Born Child"},
                new { Value = 5, Text = "Fifth Born Child"},
                new { Value = 6, Text = "Sixth Born Child"},
                new { Value = 7, Text = "Seventh Born Child"},
            }, "value", "text");

            ViewBag.SiblingRankList = siblingRank;
            ViewBag.Region = new SelectList(regions, "value", "text", 1);
            ViewBag.Province = new SelectList(provinces, "value", "text");
            ViewBag.EthnicGroupList = new SelectList(ethnic_group_list, "Id", "IndigenousMember", 0);
            ViewBag.SuffixList = new SelectList(suffixes, "id", "suffix_description", 0);
            ViewBag.ReligionList = new SelectList(religions, "ID", "Description");
            ViewBag.EducationalAttainmentList = new SelectList(educational_attainment_list, "ID", "Description");
            ViewBag.Vaccines = new SelectList(scdb.Vaccine_SC.OrderBy(p => p.vaccine_description).ToList(), "vaccine_id", "vaccine_description");
            ViewBag.IncomeClassList = new SelectList(income_class, "ID", "Description");
            ViewBag.OccupationList = new SelectList(occupation, "ID", "Description");

            return View();
        }
        public JsonResult GetSCPerson(int person_id)
        {
            var jsonResult = Json(JsonRequestBehavior.AllowGet);
            db.Configuration.ProxyCreationEnabled = false;
            try
            {
                var person = visdb.People.Where(a => a.ID == person_id).Select(a => new
                {
                    a.ID,
                    a.EthnicGroupID,
                    a.FirstName,
                    a.MiddleName,
                    a.LastName,
                    a.Suffix,
                    a.Gender,
                    a.ProvinceID,
                    a.CityMunicipalityID,
                    a.BarangayID,
                    a.ReligionID,
                    a.OccupationID,
                    a.EducationalAttainmentID,
                    a.IncomeClassID,
                    a.SiblingRank,
                    a.BirthDate,
                    a.isPWD
                }).FirstOrDefault();
                var senior_details = scdb.SeniorCitizen_details.Where(a => a.sc_person_id == person_id).Select(a => new
                {
                    a.sc_id,
                    a.sc_person_id,
                    a.sc_is_sc_member,
                    a.sc_sc_organization,
                    a.sc_previous_occupation,
                    a.sc_contact_person_name,
                    a.sc_contact_person_relationship,
                    a.sc_contact_person_contact_number,
                    a.sc_physician,
                    a.sc_physician_contact_number,
                    a.sc_living_arragement,
                    a.sc_blood_type,
                    a.sc_disablity,
                    a.sc_medical_alerts,
                    a.sc_poverty_reduction_member_id_number,
                    a.sc_is_pensioner,
                    a.sc_pensioner,
                    a.sc_philhealth_pin,
                    a.sc_sss_gsis_id_number
                }).FirstOrDefault();

                if (person == null)
                {
                    jsonResult = Json(new { isSuccess = false }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    jsonResult = Json(new { person = person, isSuccess = true }, JsonRequestBehavior.AllowGet);
                }
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult SaveVaccination(string jsonData)
        {
            var jsonResult = Json(new { });
            jsonResult.MaxJsonLength = int.MaxValue;

            try
            {
                dynamic data = JsonConvert.DeserializeObject(jsonData);

                string firstName = data["individual_first_name"];
                string lastName = data["individual_last_name"];
                string suffix = string.IsNullOrWhiteSpace(data["individual_suffix"]?.ToString()) ? null : data["individual_suffix"].ToString();

                // Get sex value with a function
                bool male = data["individual_sex_male"];
                string sexValue = GetSexValue(male);

                // Get living arrangement with a function
                bool alone = data["individual_sc_living_arrangement_alone"];
                bool spouse = data["individual_sc_living_arrangement_spouse"];
                bool children = data["individual_sc_living_arrangement_children"];
                bool others = data["individual_sc_living_arrangement_others"];
                string others_name = data["individual_sc_living_arrangement_others_name"];
                string livingArrangementValue = GetLivingArrangementValue(alone, spouse, children, others, others_name);

                bool sss = data["individual_sc_pension_sss"];
                bool gsis = data["individual_sc_pension_gsis"];
                bool pvao = data["individual_sc_pension_pvao"];
                bool others_p = data["individual_sc_pension_others"];
                string others_p_name = data["individual_sc_pension_others_name"];
                string pensionProviderValue = GetPensionerValue(sss, gsis, pvao, others_p, others_p_name);

                int ethnicGroupId;
                DateTime vaccinationDate;
                DateTime.TryParse(data["vaccination_date_of_vaccination"]?.ToString(), out vaccinationDate);
                DateTime birthDate;
                DateTime.TryParse(data["individual_date_of_birth"]?.ToString(), out birthDate);

                if (data["individual_date_of_birth"] > data["vaccination_date_of_vaccination"])
                {
                    jsonResult = Json(new { isSuccess = false, message = "Error: Vaccination date cannote be before the date of birth." }, JsonRequestBehavior.DenyGet);
                    return jsonResult;
                }
                if (DateTime.TryParse(data["vaccination_date_of_vaccination"]?.ToString(), out vaccinationDate))
                {
                    People person = new People();

                    person.EthnicGroupID = int.TryParse(data["ethnic_group_list"]?.ToString(), out ethnicGroupId) ? ethnicGroupId : (int?)null;
                    person.Suffix = suffix;
                    person.MiddleName = string.IsNullOrEmpty(data["individual_middle_name"]?.ToString()) ? "NONE" : data["individual_middle_name"].ToString().ToUpper();

                    // Not nullable values
                    person.Gender = sexValue;
                    person.FirstName = data["individual_first_name"].ToString().ToUpper();
                    person.LastName = data["individual_last_name"].ToString().ToUpper();
                    person.isPWD = data.ContainsKey("individual_pwd") && (bool)data["individual_pwd"];
                    person.SiblingRank = data["sibling_rank_list"];
                    person.ProvinceID = data["province_id"];
                    person.CityMunicipalityID = data["cm_id"];
                    person.BarangayID = data["barangay_id"];
                    person.ReligionID = data["religion_list"];
                    person.EducationalAttainmentID = data["educational_attainment_list"];
                    person.IncomeClassID = data["income_class_list"];
                    person.OccupationID = data["mrsia_occupation_list"];
                    person.BirthDate = birthDate;

                    People existingPerson = visdb.People
                        .Where(a =>
                        a.FirstName == firstName &&
                        a.LastName == lastName &&
                        a.Gender == sexValue &&
                        (string.IsNullOrEmpty(suffix) || (a.Suffix != "N/A" && a.Suffix != "NONE" && a.Suffix == suffix)) &&
                        a.BirthDate == birthDate)
                        .FirstOrDefault();

                    if (existingPerson == null)
                    {
                        visdb.People.Add(person);
                    }
                    else person = existingPerson;

                    SeniorCitizen_details scperson = new SeniorCitizen_details();

Views/VaccinationsCS/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script>
    var navItem = document.getElementById('nav-item-linelist');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('linelist-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-linelist-cs');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Master List</h1>
        <nav>
            <ol class="breadcrumb">
                @*<li class="breadcrumb-item"><a href="index.html">Home</a></li>*@
                <li class="breadcrumb-item">Vaccination</li>
                <li class="breadcrumb-item active">Index</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Default Card</h5>
                <p>
                    <a class="btn btn-primary" href="@Url.Action("PreVaccinationCS", "VaccinationsCS")"><i class="bi bi-pencil-square"></i>&nbsp;New Vaccination</a>
                </p>
                <table id="tbl-vaccinations" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th hidden>Vaccination ID</th>
                            <th style="width:30%">Person Name</th>
                            <th style="width:33%">Vaccine</th>
                            <th style="width:15%">Date of Vaccination</th>
                            <th style="width:22%">Vaccinator name</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </section>

</main><!-- End #main -->

@section scripts
{
    <!-- -------------------------------------------------------------------------------------- -->
    <!-- JavaScript Imports -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="~/Content/plugins/sweetalert2/sweetalert2.all.min.js"></script>
    <!-- Toastr -->
    <script src="~/Content/plugins/toastr/toastr.min.js"></script>
    <!-- Moment -->
    <script src="~/Content/plugins/moment/moment.min.js"></script>
    <!-- InputMask -->
    <script src="~/Content/plugins/inputmask/jquery.inputmask.min.js"></script>
    <!-- Select2 -->
    <script src="~/Content/plugins/select2/js/select2.full.min.js"></script>
    <!-- DataTables & Plugins -->
    <script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/plugins/datatables-select/js/dataTables.select.min.js"></script>
    <!--  date-range-picker-->
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- BS-Stepper-->
    <script src="~/Content/plugins/bs-stepper/js/bs-stepper.min.js"></script>
    <!-- Chart -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Page -->
    <script src="~/Scripts/Custom/common.js"></script>
    <script>
        $(document).ready(function () {
            populateVaccinationTable();
        });

        function populateVaccinationTable() {
            tblPayrolls = $('#tbl-vaccinations').DataTable({
                "destroy": true,
                "ajax": {
                    "type": "POST",
                    "url": dir + "/VaccinationsCS/VaccinationsDataTable",
                    "data": {},
                    "datatype": "json"
                },
                "responsive": true,
                "lengthChange": true,
                "autoWidth": false,
                "searching": true, // Enable global searching
                "ordering": false,
                "select": { style: 'single' },
                "columnDefs": [
                    {
                        "targets": [0],
                        "visible": false
                    },
                    {
                        render: function (data) {
                            return (moment(data).format('MMMM DD, YYYY'));
                            console.log(data)
                        },
                        targets: [3],
                        className: "text-nowrap"
                    },
                ],
                "columns": [
                    { "name": "vaccination_id", "data": "vaccination_id" },
                    { "name": "Person", "data": "Person", "width": "30%" },
                    { "name": "Vaccine", "data": "Vaccine", "width": "33%" },
                    { "name": "VaccineDate", "data": "VaccineDate", "width": "15%" },
                    { "name": "Vaccinator", "data": "Vaccinator", "width": "22%" }
                ]
            });
        }
    </script>
}