Models/Vaccination.cs
using R12VIS.Models.CustomDateValidation;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace R12VIS.Models
{
    public class Vaccination
    {
        public int ID { get; set; }

        [ForeignKey("PriorityGroup")]
        public int PriorityGroupID { get; set; }
        public PriorityGroup PriorityGroup { get; set; }

        public string Comorbidity { get; set; }

        [ForeignKey("Person")]
        public int PersonID { get; set; }
        public Person Person { get; set; }

        [ForeignKey("Deferral")]
        public int? DeferralID { get; set; }
        public Deferral Deferral { get; set; }

        [DateFormatValidation(ErrorMessage = "Invalid Vaciination Date")]
        [DataType(DataType.Date)]
        public DateTime? VaccinationDate { get; set; }

        [ForeignKey("Vaccine")]
        public int VaccineID { get; set; }
        public Vaccine Vaccine { get; set; }

        [Display(Name = "Batch Number")]
        public string BatchNumber { get; set; }

        [Display(Name = "Lot Number")]
        public string LotNumber { get; set; }

        [Display(Name = "Bakuna Center CBCR ID")]
        public string BakunaCenterCBCRID { get; set; }

        [Display(Name = "Vaccinator Name")]
        public string VaccinatorName { get; set; }

        public int DoseID { get; set; }
        public Dose Dose { get; set; }

        [Display(Name = "Adverse Event")]
        public int? AdverseID { get; set; }
        public Adverse Adverse { get; set; }

        [DateFormatValidation(ErrorMessage = "Invalid date")]
        [DataType(DataType.Date)]
        public DateTime DateCreate { get; set; } = DateTime.Now.Date;

        public string CreatedBy { get; set; }

        [ForeignKey("User")]
        public int? UserID { get; set; }
        public User User { get; set; }
    }
}

Controllers/VaccinationsController.cs
using R12VIS.Models;
using R12VIS.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace R12VIS.Controllers
{
    [UserAuthenticationFilter]
    public class VaccinationsController : Controller
    {
        private DbContextR12 db = new DbContextR12();


        // GET: Vaccinations
        public ActionResult Index()
        {

            return View();

            //var vaccinations = db.Vaccinations.Select(v => new {
            //    v.Adverse,
            //    v.Deferral,
            //    v.Dose,
            //    v.Person,
            //    v.PriorityGroup,
            //    v.Vaccine,
            //    v.Person.EthnicGroup,
            //    v.Person.Province,
            //    v.Person.CityMunicipality,
            //    v.Person.Barangay
            //}).ToList();
            //return View(vaccinations); /**/
        }

        // GET: Vaccinations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaccination vaccination = db.Vaccinations.Find(id);
            if (vaccination == null)
            {
                return HttpNotFound();
            }
            return View(vaccination);
        }

        // GET: Vaccinations/Create
        public ActionResult Create()
        {
            ViewBag.AdverseID = new SelectList(db.Adverses, "ID", "Event");
            ViewBag.DeferralID = new SelectList(db.Deferrals, "Id", "Reason");
            ViewBag.DoseID = new SelectList(db.Dose, "ID", "VaccineDose");
            ViewBag.PersonID = new SelectList(db.Persons, "ID", "UniquePersonID");
            ViewBag.PriorityGroupID = new SelectList(db.PriorityGroups, "ID", "Category");
            ViewBag.VaccineID = new SelectList(db.Vaccines, "ID", "VaccineManufacturer");
            return View();
        }

        // POST: Vaccinations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PriorityGroupID,PersonID,ProvinceID,CityMunicipalityID,BarangayID,DeferralID,VaccinationDate,VaccineID,BatchNumber,LotNumber,BakunaCenterCBCRID,VaccinatorName,DoseID,AdverseID")] Vaccination vaccination)
        {
            if (ModelState.IsValid)
            {
                db.Vaccinations.Add(vaccination);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AdverseID = new SelectList(db.Adverses, "ID", "Event", vaccination.AdverseID);
            ViewBag.DeferralID = new SelectList(db.Deferrals, "Id", "Reason", vaccination.DeferralID);
            ViewBag.DoseID = new SelectList(db.Dose, "ID", "VaccineDose", vaccination.DoseID);
            ViewBag.PersonID = new SelectList(db.Persons, "ID", "UniquePersonID", vaccination.PersonID);
            ViewBag.PriorityGroupID = new SelectList(db.PriorityGroups, "ID", "Category", vaccination.PriorityGroupID);
            ViewBag.VaccineID = new SelectList(db.Vaccines, "ID", "VaccineManufacturer", vaccination.VaccineID);
            return View(vaccination);
        }

        // GET: Vaccinations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vaccination vaccination = db.Vaccinations
                .Include(x => x.Person)
                .Where(x => x.ID == id)
                .FirstOrDefault();
            if (vaccination == null)
            {
                return HttpNotFound();
            }
            ViewBag.PriorityGroupID = new SelectList(db.PriorityGroups, "ID", "Category", vaccination.PriorityGroupID);
            var ethnicGroups = db.EthnicGroups.ToList();
            ethnicGroups.Insert(0, new EthnicGroup { Id = 0, IndigenousMember = "" });
            ViewBag.EthnicGroupID = new SelectList(ethnicGroups, "Id", "IndigenousMember", vaccination.Person.EthnicGroupID);
            ViewBag.ProvinceID = new SelectList(db.Provinces.Where(a => a.RegionID == 1).OrderBy(p => p.province_name), "province_id", "province_name", vaccination.Person.ProvinceID);
            ViewBag.CityMunicipalityID = new SelectList(db.CityMunicipalities.OrderBy(p => p.CityMunicipalityName), "city_municipality_id", "CityMunicipalityName", vaccination.Person.CityMunicipalityID);
            ViewBag.BarangayID = new SelectList(db.Barangays.OrderBy(p => p.barangay_name).Take(100), "barangay_id", "barangay_name", vaccination.Person.BarangayID);
            ViewBag.DeferralID = new SelectList(db.Deferrals.OrderBy(p => p.Reason).Take(100), "Id", "Reason", vaccination.DeferralID);
            ViewBag.VaccineID = new SelectList(db.Vaccines.OrderBy(p => p.VaccineManufacturer), "ID", "VaccineManufacturer", vaccination.VaccineID);
            ViewBag.DoseID = new SelectList(db.Dose.OrderBy(p => p.ID), "ID", "VaccineDose", vaccination.DoseID);
            ViewBag.AdverseID = new SelectList(db.Adverses.OrderBy(p => p.ID), "ID", "Condition", vaccination.AdverseID);
            ViewBag.Religion = new SelectList(db.Religions.OrderBy(p => p.ID), "ID", "Description", vaccination.Person.ReligionID);
            ViewBag.EducationalAttainment = new SelectList(db.EducationalAttainment.OrderBy(p => p.ID), "ID", "Description", vaccination.Person.EducationalAttainment);
            ViewBag.IncomeClass = new SelectList(db.IncomeClass.OrderBy(p => p.ID), "ID", "Description", vaccination.Person.IncomeClass);
            ViewBag.Occupation = new SelectList(db.Occupation.OrderBy(p => p.ID), "ID", "Description", vaccination.Person.Occupation);

            SelectList siblingRank = new SelectList(new[]
            {
                new { Value = 1, Text = "First Born Child"},
                new { Value = 2, Text = "Second Born Child"},
                new { Value = 3, Text = "Third Born Child"},
                new { Value = 4, Text = "Fourth Born Child"},
                new { Value = 5, Text = "Fifth Born Child"},
                new { Value = 6, Text = "Sixth Born Child"},
                new { Value = 7, Text = "Seventh Born Child"},
            }, "Value", "Text", vaccination.Person.SiblingRank);
            ViewBag.SiblingRank = siblingRank;

            SelectList gender = new SelectList(new[]
            {
                new {Value = "M", Text = "Male"},
                new {Value = "F", Text = "Female"}
            }, "Value", "Text", vaccination.Person.Gender);

            SelectList suffix = new SelectList(new[]
            {
                new {Value =String.Empty, Text ="NA"},
                new { Value = "II", Text = "II"},
                new { Value = "III", Text = "III"},
                new { Value = "IV", Text = "IV"},
                new { Value = "V", Text = "V"},
                new { Value = "SR.", Text = "SR."},
                new { Value = "JR.", Text = "JR."},
            }, "Value", "Text", vaccination.Person.Suffix);

            ViewBag.Suffix = suffix;
            ViewBag.Gender = gender;

            return View(vaccination);
        }

        // POST: Vaccinations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vaccination vaccination)
        {
            if (ModelState.IsValid)
            {
                vaccination.Person.FirstName = vaccination.Person.FirstName?.ToUpper();
                vaccination.Person.LastName = vaccination.Person.LastName?.ToUpper();
                vaccination.Person.MiddleName = vaccination.Person.MiddleName?.ToUpper();
                vaccination.Person.Suffix = vaccination.Person.Suffix?.ToUpper();
                vaccination.VaccinatorName = vaccination.VaccinatorName?.ToUpper();
                vaccination.Comorbidity = vaccination.Comorbidity?.ToUpper();
                db.Entry(vaccination).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PriorityGroupID = new SelectList(db.PriorityGroups, "ID", "Category", vaccination.PriorityGroupID);
            var ethnicGroups = db.EthnicGroups.ToList();
            ethnicGroups.Insert(0, new EthnicGroup { Id = 0, IndigenousMember = "" });
            ViewBag.EthnicGroupID = new SelectList(db.EthnicGroups, "Id", "IndigenousMember", vaccination.Person.EthnicGroupID);
            ViewBag.ProvinceID = new SelectList(db.Provinces.Where(a => a.RegionID == 1).OrderBy(p => p.province_name), "province_id", "province_name", vaccination.Person.ProvinceID);
            ViewBag.CityMunicipalityID = new SelectList(db.CityMunicipalities.OrderBy(p => p.CityMunicipalityName), "city_municipality_id", "CityMunicipalityName", vaccination.Person.CityMunicipalityID);
            ViewBag.BarangayID = new SelectList(db.Barangays.OrderBy(p => p.barangay_name).Take(100), "barangay_id", "barangay_name", vaccination.Person.BarangayID);
            ViewBag.DeferralID = new SelectList(db.Deferrals.OrderBy(p => p.Reason).Take(100), "Id", "Reason", vaccination.DeferralID);
            ViewBag.VaccineID = new SelectList(db.Vaccines.OrderBy(p => p.VaccineManufacturer), "ID", "VaccineManufacturer", vaccination.VaccineID);
            ViewBag.DoseID = new SelectList(db.Dose.OrderBy(p => p.ID), "ID", "VaccineDose", vaccination.DoseID);
            ViewBag.AdverseID = new SelectList(db.Adverses.OrderBy(p => p.ID), "ID", "Condition", vaccination.AdverseID);

Views/Vaccinations/BlankPage.cshtml
@{
    ViewBag.Title = "BlankPage";
}



<main id="main" class="main">

    <div class="pagetitle">
        <h1>Blank Page</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Pages</li>
                <li class="breadcrumb-item active">Blank</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Title of blank page</h5>
                <h2>BlankPage</h2>
            </div>
        </div>
    </section>

</main><!-- End #main -->

Views/Vaccinations/Create.cshtml
@model R12VIS.Models.Vaccination

@{
    ViewBag.Title = "Create";
}

<script>
    var navItem = document.getElementById('nav-item-vaccination');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('vaccinations-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-vaccinations-covid');
    navLinkChild.classList.remove('collapsed');
</script>

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vaccination</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PriorityGroupID, "PriorityGroupID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PriorityGroupID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PriorityGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProvinceID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProvinceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityMunicipalityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityMunicipalityID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityMunicipalityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BarangayID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BarangayID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BarangayID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeferralID, "DeferralID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeferralID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeferralID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VaccinationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VaccinationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VaccinationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VaccineID, "VaccineID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VaccineID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VaccineID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatchNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BatchNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatchNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LotNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LotNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LotNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BakunaCenterCBCRID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BakunaCenterCBCRID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BakunaCenterCBCRID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VaccinatorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VaccinatorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VaccinatorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoseID, "DoseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DoseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DoseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdverseID, "AdverseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AdverseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdverseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Vaccinations/Delete.cshtml
@model R12VIS.Models.Vaccination

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vaccination</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adverse.Event)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adverse.Event)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deferral.Reason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deferral.Reason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dose.VaccineDose)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dose.VaccineDose)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.UniquePersonID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.UniquePersonID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriorityGroup.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriorityGroup.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vaccine.VaccineManufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vaccine.VaccineManufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProvinceID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvinceID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityMunicipalityID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityMunicipalityID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BarangayID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BarangayID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VaccinationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VaccinationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LotNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LotNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BakunaCenterCBCRID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BakunaCenterCBCRID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VaccinatorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VaccinatorName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Vaccinations/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script>
    var navItem = document.getElementById('nav-item-linelist');
    navItem.classList.remove('collapsed');
    var navLink = document.getElementById('linelist-nav');
    navLink.classList.remove('collapse');
    var navLinkChild = document.getElementById('nav-item-link-linelist-covid');
    navLinkChild.classList.remove('collapsed');
</script>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>COVID Linelist</h1>
        <nav>
            <ol class="breadcrumb">
                @*<li class="breadcrumb-item"><a href="index.html">Home</a></li>*@
                <li class="breadcrumb-item">Vaccination</li>
                <li class="breadcrumb-item active">Linelist</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">COVID Vaccination list</h5>

                <p>
                    <a class="btn btn-primary" href="@Url.Action("PreVaccination", "Vaccinations")"><i class="bi bi-pencil-square"></i>&nbsp;New Vaccination</a>
                </p>
                <table id="tbl-vaccinations" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th style="width:31%">Person Name</th>
                            <th style="width:17%">Vaccine Brand</th>
                            <th style="width:22%">Dose No.</th>
                            <th style="width:20%">Priority Group</th>
                            <th style="width:10%">Ethnic Group</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </section>

</main><!-- End #main -->

@section scripts
{
    <script src="~/Content/DataTable/cdn.datatables.net_1.13.4_js_jquery.dataTables.min.js"></script>
    <script src="~/Content/DataTable2/datatables.min.js"></script>
    <script src="~/Scripts/Custom/common.js"></script>
    <script>
        $(document).ready(function () {
            populateVaccinationTable();
        });

        function populateVaccinationTable() {
            tblPayrolls = $('#tbl-vaccinations').DataTable({
                "destroy": true,
                "ajax": {
                    "type": "POST",
                    "url": dir + "/Vaccinations/VaccinationsDataTable",
                    "data": {},
                    "datatype": "json"
                },
                "responsive": true,
                "lengthChange": true,
                "autoWidth": false,
                "searching": true, // Enable global searching
                "ordering": false,
                "select": { style: 'single' },
                "columnDefs": [
                    {
                        "targets": [0],
                        "visible": false
                    },
                    {
                        "targets": [1], // Index of the "Person" column
                        "searchable": true, // Enable searching for this column
                    }
                ],
                "columns": [
                    { "name": "ID", "data": "ID" },
                    { "name": "Person", "data": "Person", "width": "31%" },
                    { "name": "Vaccine", "data": "Vaccine", "width": "17%" },
                    { "name": "Dose", "data": "Dose", "width": "22%" },
                    { "name": "Priority", "data": "Priority", "width": "20%" },
                    { "name": "Ethnic", "data": "Ethnic", "width": "10%" }
                ]
            });
        }
    </script>
}